// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void BtnDistClick(lv_event_t * e);
void PnlXClick(lv_event_t * e);
void PnlYClick(lv_event_t * e);
void PnlZClick(lv_event_t * e);
void HomeClick(lv_event_t * e);
void QGLClick(lv_event_t * e);
void ConfigClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
