// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void PnlXClick(lv_event_t * e)
{
	// Your code here
}

void PnlYClick(lv_event_t * e)
{
	// Your code here
}

void PnlZClick(lv_event_t * e)
{
	// Your code here
}

void HomeClick(lv_event_t * e)
{
	// Your code here
}

void QGLClick(lv_event_t * e)
{
	// Your code here
}

void ConfigClick(lv_event_t * e)
{
	// Your code here
}
