// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnHome = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BtnHome, 166);
    lv_obj_set_height(ui_BtnHome, 55);
    lv_obj_set_x(ui_BtnHome, 0);
    lv_obj_set_y(ui_BtnHome, -129);
    lv_obj_set_align(ui_BtnHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnHome, lv_color_hex(0xFABC1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnQGL = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BtnQGL, 166);
    lv_obj_set_height(ui_BtnQGL, 55);
    lv_obj_set_x(ui_BtnQGL, 0);
    lv_obj_set_y(ui_BtnQGL, -68);
    lv_obj_set_align(ui_BtnQGL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnQGL, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnQGL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnQGL, lv_color_hex(0xFFBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnQGL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnConfig = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BtnConfig, 166);
    lv_obj_set_height(ui_BtnConfig, 55);
    lv_obj_set_x(ui_BtnConfig, 0);
    lv_obj_set_y(ui_BtnConfig, 65);
    lv_obj_set_align(ui_BtnConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnExit = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BtnExit, 166);
    lv_obj_set_height(ui_BtnExit, 55);
    lv_obj_set_x(ui_BtnExit, 0);
    lv_obj_set_y(ui_BtnExit, 126);
    lv_obj_set_align(ui_BtnExit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnExit, lv_color_hex(0xF27676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 125);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "EXIT");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 64);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "CONFIG");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -2);
    lv_obj_set_y(ui_Label6, -129);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "HOME");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -2);
    lv_obj_set_y(ui_Label7, -70);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "QGL");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnHome, ui_event_BtnHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnQGL, ui_event_BtnQGL, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnConfig, ui_event_BtnConfig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnExit, ui_event_BtnExit, LV_EVENT_ALL, NULL);

}
